### PR TITLE
Move from CodeDepends back to codetools for static code analysis

### PR DESCRIPTION
**Pull request by wlandau**
# Summary

Reasons:

1. From #421, we actually do need to detect non-standard evaluation variables. That means `CodeDepends::getInputs()` does not add value to `drake` relative to `codetools::findGlobals()`.
2. The only part of `CodeDepends` relevant to `drake` is `getInputs()`.
3. `CodeDepends` depends on `graph`, which is a BioConductor package. That creates installation friction (ref: https://github.com/duncantl/CodeDepends/issues/34).
4. From https://github.com/duncantl/CodeDepends/issues/30#issuecomment-399799316, (3) is not likely to change anytime soon.

# Related GitHub issues

- Ref: #421, https://github.com/duncantl/CodeDepends/issues/30, https://github.com/duncantl/CodeDepends/issues/34

# Checklist

- [x] I have read `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CONDUCT.md), and I agree to follow its rules.
- [x] I have read the [guidelines for contributing](https://github.com/ropensci/drake/blob/master/CONTRIBUTING.md).
- [x] I have listed any substantial changes in the [development news](https://github.com/ropensci/drake/blob/master/NEWS.md).
- [x] I have added [`testthat`](https://github.com/r-lib/testthat) unit tests to [`tests/testthat`](https://github.com/ropensci/drake/tree/master/tests/testthat) to confirm that any new features or functionality work correctly.
- [x] I have tested this pull request locally with `devtools::check()`
- [x] This pull request is ready for review.
- [x] I think this pull request is ready to merge.

### CODE REVIEW

**Comment by krlmlr** [comment]
Thanks, this does reduce friction indeed (and gets rid of that annoying warning when loading _drake_, too).

I was wondering if _drake_ can be used with a lighter-weight code analysis. In a "void" run where all targets are up to date, the code analysis takes about half the time (6 out of 12 seconds) in a fairly small project. I'm thinking about the following mode of operation:

- (non-function) imports are ignored, `make()` is run from an empty environment that is a child of the parent environment of `.GlobalEnv`
- only dependencies between functions are checked and cached; this allows for fast turnarounds when nothing has changed
    - for each function, the descendant function(s) they call are cached
    - the function is invalidated if the code changed or any one of the descendants changes
    - a descendant changes if its code changed or any of its sub-descendants changes, etc.
    - this means code analysis is only necessary when the code changed, and then only partially
- _drake_ always starts with a stable set of loaded and attached packages, and warns/errs if `make()` is called with a different setup

I was also thinking about making all imports explicit, but I'm not sure I like this approach:

```r
drake_plan(
  data = readr::read_csv(file_in("test.csv")),
  processed_data = f(data, g, h),

  f = function(data, g, h) {
    data %>% g(1) %>% h(2, 3)
  },

  g = function(data, x) {
    data %>% mutate(a = a + x)
  },

  h = function(data, y, z) {
    data %>% mutate(b = b * y - z)
  }
)
```

Another issue with deep code analysis is that it is fooled by NSE -- columns accessed in `select()` et al. are recognized as missing imports.

I'm aware that several issues are convoluted here, happy to discuss first before opening new issues. Some of the requested features may well be implemented already.

**Comment by wlandau** [comment]
We stand to gain a little from (1).

``` r
microbenchmark::microbenchmark(codetools::findGlobals(digest::digest))
#> Unit: milliseconds
#>                                    expr     min       lq     mean  median
#>  codetools::findGlobals(digest::digest) 10.9823 11.53732 12.52918 11.6991
#>        uq      max neval
#>  12.53337 36.68236   100
microbenchmark::microbenchmark(drake:::code_dependencies(digest::digest))
#> Unit: milliseconds
#>                                       expr      min      lq    mean
#>  drake:::code_dependencies(digest::digest) 57.30964 59.8394 70.9948
#>    median      uq      max neval
#>  61.25208 63.7505 872.1631   100
```

From (2), I am not so sure. Users can avoid the whole problem by holding onto a `drake_config()` object.

**Comment by krlmlr** [comment]
(2) Is there a way to "refresh" a configuration object? I memoize a `drake_config()` object, then change some code. How do I update the memoized object so that the (potentially new) code dependencies are reflected? Is the update faster than recreating the whole config?

**Comment by wlandau** [comment]
So maybe my claim about avoiding the whole problem was too strong. There is no graceful or fast way to refresh a `drake_config()` object so that new dependencies are reflected in the schedule/graph, but changes to existing dependencies are detected without the need for a refresh.

**Comment by clarkfitzg** [comment]
Another option to identify global variables: https://github.com/HenrikBengtsson/globals

**Comment by wlandau** [comment]
Definitely worth a look. `globals::findGlobals()` expands on `codetools::findGlobals()` by making the code analysis more explicit and supporting multiple search algorithms. I think I could learn a lot by studying [`globals/R/findGlobals.R`](https://github.com/HenrikBengtsson/globals/blob/d372fbec768643674d9ae11dc964f3ab29d8ecd0/R/findGlobals.R) and maybe eventually detect all the globals during `drake`'s own code analysis. As for switching from `codetools` to `globals`, I think it would add more package dependencies (since `globals` depends on `codetools`) and I am not convinced by the benchmarks.

``` r
microbenchmark::microbenchmark(
  codetools::findGlobals(future.apply::future_lapply),
  globals::findGlobals(future.apply::future_lapply, method = "ordered"),
  globals::findGlobals(future.apply::future_lapply, method = "conservative"),
  globals::findGlobals(future.apply::future_lapply, method = "liberal"),
  times = 1e3
)
#> Unit: milliseconds
#>                                                                        expr
#>                         codetools::findGlobals(future.apply::future_lapply)
#>       globals::findGlobals(future.apply::future_lapply, method = "ordered")
#>  globals::findGlobals(future.apply::future_lapply, method = "conservative")
#>       globals::findGlobals(future.apply::future_lapply, method = "liberal")
#>       min       lq     mean   median       uq      max neval
#>  12.66153 13.41950 14.45891 14.47443 14.98748 43.46495  1000
#>  14.58711 15.37591 16.68439 16.53618 17.09585 53.85675  1000
#>  12.67186 13.34511 14.36733 14.36671 14.95802 45.77409  1000
#>  12.61083 13.34331 14.40460 14.38573 14.98405 43.71020  1000
microbenchmark::microbenchmark(
  codetools::findGlobals(digest::digest),
  globals::findGlobals(digest::digest, method = "ordered"),
  globals::findGlobals(digest::digest, method = "conservative"),
  globals::findGlobals(digest::digest, method = "liberal"),
  times = 1e3
)
#> Unit: milliseconds
#>                                                           expr      min
#>                         codetools::findGlobals(digest::digest) 5.425160
#>       globals::findGlobals(digest::digest, method = "ordered") 5.687805
#>  globals::findGlobals(digest::digest, method = "conservative") 5.324367
#>       globals::findGlobals(digest::digest, method = "liberal") 5.312320
#>        lq     mean   median       uq       max neval
#>  5.562746 6.080788 5.735257 6.309940 31.356794  1000
#>  5.848301 6.394264 6.040293 6.746562 31.215894  1000
#>  5.489772 5.931004 5.670860 5.952348 30.880753  1000
#>  5.475589 5.926636 5.659490 6.171142  8.098277  1000
microbenchmark::microbenchmark(
  codetools::findGlobals(lm),
  globals::findGlobals(lm, method = "ordered"),
  globals::findGlobals(lm, method = "conservative"),
  globals::findGlobals(lm, method = "liberal"),
  times = 1e3
)
#> Unit: milliseconds
#>                                               expr      min       lq
#>                         codetools::findGlobals(lm) 6.666464 6.968272
#>       globals::findGlobals(lm, method = "ordered") 8.121782 8.445097
#>  globals::findGlobals(lm, method = "conservative") 6.617390 6.886321
#>       globals::findGlobals(lm, method = "liberal") 6.603975 6.886380
#>      mean   median       uq      max neval
#>  7.573066 7.198253 8.230855 37.32475  1000
#>  9.209107 8.747746 9.830884 34.58360  1000
#>  7.482776 7.092501 7.976657 34.97287  1000
#>  7.527133 7.138773 8.108652 33.74470  1000
```

**Pull request merged**
