### PR TITLE
Reproducible session management

### PR DESCRIPTION
**Pull request by wlandau**
# Summary

This PR implements the proposal in https://github.com/ropensci/drake/issues/761#issuecomment-468940771. We can achieve reproducible session management if we rely on a master R script file that returns a `drake_config()` object. See the help file of `r_make()` for details. Usage:

``` r
writeLines(
  c(
    "library(drake)",
    "load_mtcars_example()",
    "drake_config(my_plan)"
  ),
  "_drake.R" # default value of the `source` argument
)
cat(readLines("_drake.R"), sep = "\n")
#> library(drake)
#> load_mtcars_example()
#> drake_config(my_plan)

library(drake)
r_outdated()
#>  [1] "coef_regression1_large" "coef_regression1_small"
#>  [3] "coef_regression2_large" "coef_regression2_small"
#>  [5] "large"                  "regression1_large"     
#>  [7] "regression1_small"      "regression2_large"     
#>  [9] "regression2_small"      "report"                
#> [11] "small"                  "summ_regression1_large"
#> [13] "summ_regression1_small" "summ_regression2_large"
#> [15] "summ_regression2_small"
r_make()
r_outdated()
#> character(0)
```

<sup>Created on 2019-03-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Packages `callr` + `parallel` (forks specifically) can be a dangerous combination (ref: https://github.com/r-lib/processx/issues/113) but simple tests of multicore `clustermq` and `future` parallelism seem to run just fine in `r_make()`.

cc:

- @MilesMcBain
- @rkrug
- @noamross

# Related GitHub issues and pull requests

- Ref: #761

# Checklist

- [x] I have read `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CONDUCT.md), and I agree to follow its rules.
- [x] I have listed any substantial changes in the [development news](https://github.com/ropensci/drake/blob/master/NEWS.md).
- [x] I have added [`testthat`](https://github.com/r-lib/testthat) unit tests to [`tests/testthat`](https://github.com/ropensci/drake/tree/master/tests/testthat) to confirm that any new features or functionality work correctly.
- [x] I have tested this pull request locally with `devtools::check()`
- [x] This pull request is ready for review.
- [ ] I think this pull request is ready to merge.

### CODE REVIEW

**Comment by wlandau** [comment]
We can discuss the design and usage at the [Chicago R Unconference](https://chirunconf.github.io) and wait to merge until after version 7.0.0 is accepted to CRAN.

**Comment by wlandau** [comment]
Merging, re https://github.com/ropensci/drake/issues/761#issuecomment-469019843.

**Comment by lorenzwalthert** [comment]
This might be a dumb question but what exactly is the advantage of the approach with `r_make()` compared to running a fresh R session from the terminal, sourcing relevant scripts and build the plan (e.g. in RStudio as a build rutine)? I think we talked about it at some point but I could not find it anymore. I wrote a blog post about this (and other things) which I have not published yet (and which I think I have to review in the light of the 0.7 release). You can preview here: https://5c6f2832b2861fbc63604c01--lorenzwalthert.netlify.com/post/drake-workflow-proposal/

**Comment by wlandau** [comment]
It is mainly about childproofing. It is easy to forget to start a fresh session and source the correct setup scripts in the correct order, especially for new users, and the consequences of getting it wrong are painful. It also turns out to be convenient in practice. I am using `r_vis_drake_graph()` a lot for my own internal workflows, and I feel like I can relax and trust the tool lot more.

**Comment by wlandau** [comment]
Also, I skimmed the draft of your blog post, and those are some super valuable workarounds for `drake` <= 6.2.1. Sorry about the timing. As you were writing, the functionality and best practices were changing. You might have a look at the [new DSL](https://ropenscilabs.github.io/drake-manual/plans.html#large-plans) and the [newly revamped chapter on projects](https://ropenscilabs.github.io/drake-manual/projects.html).

Things I like about your post that are still current:

- Running `drake` in the background. If your workflow runs long enough for `drake` to be useful, you are probably going to want to run it in batch mode in the background anyway.
- Unit tests inside a `drake` workflow.
- `drogger`. `drake` tries not to work too hard at console logging, and I think this fills a gap.

**Comment by lorenzwalthert** [comment]
Thanks, I will have a look at the two links. The reason this post was not published is because drogger and teamtools is not ready for prime time. Also, I think other packages such as drogger can fill the logging gap. It helps keeping drake lightweight and also it is kind of orthogonal to drake because logging has many other applications.

**Pull request merged**
