### PR TITLE
Dynamic branching

### PR DESCRIPTION
**Pull request by wlandau**
# Summary

At long last, `drake` is capable of dynamic branching! You can now define new targets while `make()` is running.

Here is an demo that fits GDP vs year for each country in the [Gapminder dataset](https://github.com/jennybc/gapminder). We let the data decide how many targets we have and what those targets mean.

``` r
library(broom)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(drake)
library(gapminder) # https://github.com/jennybc/gapminder

# We need a function to fit the model.
fit_model <- function(dataset, country) {
  dataset %>%
    filter(country == country) %>%
    lm(formula = gdpPercap ~ year) %>%
    tidy() %>%
    mutate(country = country)
}

plan <- drake_plan(
  # This dataset can change, and we want
  # the downstream targets to update.
  dataset = gapminder,
  
  # We need a grouping variable for our dynamic
  # targets (e.g. models).
  country = unique(dataset$country),
  
  # Fit GDP vs year for each country.
  model = target(
    fit_model(dataset, country),
    dynamic = map(country)
  ),
  
  # Get the continent of each model's country.
  continent = dataset %>%
    distinct(continent, country) %>%
    pull(continent),
  
  # Aggregate the models by continent.
  results = target(
    bind_rows(model) %>%
      mutate(continent = continent),
    dynamic = combine(model, .by = continent)
  )
)

# The targets have cryptic names,
# but there are good reasons to use hashes as suffixes.
# I will discuss if someone wants to.
make(plan)
#> target dataset
#> target country
#> target continent
#> subtarget model_94c60fa4
#> subtarget model_d80d49db
#> subtarget model_1dc4c7bc
#> subtarget model_63e3125f
#> subtarget model_29837144
#> subtarget model_cdf5fd51
##### Messages manually cropped because there are lots of models...
#> subtarget results_ec495f2f
#> subtarget results_ebc11748
#> subtarget results_36a21b31
#> subtarget results_73b41ee9
#> subtarget results_5b99ead0

# loadd() and readd() understand dynamic targets,
# so you do not need to deal with those funny names.
readd(results, subtargets = seq_len(2))
#> [[1]]
#> # A tibble: 66 x 7
#>    term        estimate std.error statistic  p.value country     continent
#>    <chr>          <dbl>     <dbl>     <dbl>    <dbl> <fct>       <fct>    
#>  1 (Intercept) -249694.   26678.      -9.36 2.45e-20 Afghanistan Asia     
#>  2 year            130.      13.5      9.63 2.07e-21 Afghanistan Asia     
#>  3 (Intercept) -249694.   26678.      -9.36 2.45e-20 Bahrain     Asia     
#>  4 year            130.      13.5      9.63 2.07e-21 Bahrain     Asia     
#>  5 (Intercept) -249694.   26678.      -9.36 2.45e-20 Bangladesh  Asia     
#>  6 year            130.      13.5      9.63 2.07e-21 Bangladesh  Asia     
#>  7 (Intercept) -249694.   26678.      -9.36 2.45e-20 Cambodia    Asia     
#>  8 year            130.      13.5      9.63 2.07e-21 Cambodia    Asia     
#>  9 (Intercept) -249694.   26678.      -9.36 2.45e-20 China       Asia     
#> 10 year            130.      13.5      9.63 2.07e-21 China       Asia     
#> # … with 56 more rows
#> 
#> [[2]]
#> # A tibble: 60 x 7
#>    term      estimate std.error statistic  p.value country        continent
#>    <chr>        <dbl>     <dbl>     <dbl>    <dbl> <fct>          <fct>    
#>  1 (Interce… -249694.   26678.      -9.36 2.45e-20 Albania        Europe   
#>  2 year          130.      13.5      9.63 2.07e-21 Albania        Europe   
#>  3 (Interce… -249694.   26678.      -9.36 2.45e-20 Austria        Europe   
#>  4 year          130.      13.5      9.63 2.07e-21 Austria        Europe   
#>  5 (Interce… -249694.   26678.      -9.36 2.45e-20 Belgium        Europe   
#>  6 year          130.      13.5      9.63 2.07e-21 Belgium        Europe   
#>  7 (Interce… -249694.   26678.      -9.36 2.45e-20 Bosnia and He… Europe   
#>  8 year          130.      13.5      9.63 2.07e-21 Bosnia and He… Europe   
#>  9 (Interce… -249694.   26678.      -9.36 2.45e-20 Bulgaria       Europe   
#> 10 year          130.      13.5      9.63 2.07e-21 Bulgaria       Europe   
#> # … with 50 more rows

# The graphs for large workflows are much simpler to look at now.
config <- drake_config(plan)
vis_drake_graph(config)
```

``` r

# Side note: plans have a plot method now.
plot(plan)
```

<sup>Created on 2019-11-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

# Performance

Dynamic branching makes `drake_config()` and `outdated()` much faster, which makes `make()` much faster to initialize. However, when it comes to building targets, the [per-target overhead for dynamic sub-targets](https://github.com/ropensci/drake/issues/685#issuecomment-549090877) can be twice that of static branching. Not such a big deal for a first implementation. After all, it took a long time to get static branching as fast as it is. But performance will always be a long-term project.

# Related GitHub issues and pull requests

- Ref: #685

# Checklist

- [x] I understand and agree to `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] I have listed any substantial changes in the [development news](https://github.com/ropensci/drake/blob/master/NEWS.md).
- [x] I have added [`testthat`](https://github.com/r-lib/testthat) unit tests to [`tests/testthat`](https://github.com/ropensci/drake/tree/master/tests/testthat) for any new functionality.
- [x] This pull request is not a [draft](https://github.blog/2019-02-14-introducing-draft-pull-requests).

### CODE REVIEW

**Comment by wlandau** [comment]
More details and dicussion: https://github.com/ropensci/drake/issues/685#issuecomment-549096373

**Comment by wlandau** [comment]
Forgot to mention: for anything without a `dim()`, we map over the elements. For anything with a `dim()`, we map over the first margin. This makes it super easy to map over the rows.

``` r
library(drake)
library(tibble)
plan <- drake_plan(
  x = as_tibble(mtcars),
  y = target(x, dynamic = map(x))
)

make(plan, verbose = 0L)

readd(y, subtargets = 1:2)
#> [[1]]
#> # A tibble: 1 x 11
#>     mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
#>   <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#> 1    21     6   160   110   3.9  2.62  16.5     0     1     4     4
#> 
#> [[2]]
#> # A tibble: 1 x 11
#>     mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
#>   <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#> 1    21     6   160   110   3.9  2.88  17.0     0     1     4     4
```

<sup>Created on 2019-11-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wlandau** [comment]
Also note mapping over rows:

**Comment by wlandau** [comment]
https://github.com/ropensci/drake/pull/1042#issuecomment-549096614

**Comment by kendonB** [comment]
> for anything without a dim(), we map over the elements. For anything with a dim(), we map over the first margin. This makes it super easy to map over the rows.

I anticipate that this will cause confusion in the case of data.frames. It might be better to have verbose control over which way the iteration goes. This is especially true for `map` as the `purrr` function iterates over `[[` i.e. columns in the case of data.frames.

Consider having lots of map options like in `purrr`?

**Comment by kendonB** [comment]
This looks really cool! 

How would I get the subtarget associated with a particular value of country here? 

```
readd(results, subtargets = seq_len(2))
```

**Comment by wlandau** [comment]
Re https://github.com/ropensci/drake/pull/1042#issuecomment-549163578, I will think about it, but please do not get your hopes up. Row-oriented workflows come up a lot more than looping over columns, so I want the former to take priority. And other workarounds like `map_rows()` have even more explaining to do when we start thinking about mapping over a mix of data frames and non-data-frames.

Anyway, here is how to get the model for a country and the aggregate for a continent. There is no general way to assign suggestive names during `make()`, so `drake` does not even try. (Consistency in all cases is better than convenience in some.) When you do read the sub-target, please take a look at the `country` or `continent` column to make sure your read the right value.

``` r
library(broom)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(drake)
library(gapminder)

fit_model <- function(dataset, country) {
  dataset %>%
    filter(country == !!country) %>%
    lm(formula = gdpPercap ~ year) %>%
    tidy() %>%
    mutate(country = !!country)
}

plan <- drake_plan(
  dataset = gapminder,
  country = unique(dataset$country),
  model = target(
    fit_model(dataset, country),
    dynamic = map(country)
  ),
  continent = dataset %>%
    distinct(continent, country) %>%
    pull(continent),
  results = target(
    bind_rows(model) %>%
      mutate(continent = continent),
    dynamic = combine(model, .by = continent)
  )
)

make(plan, verbose = 0L)

countries <- readd(country)
index <- which(countries == "Philippines")
readd(model, subtargets = index)[[1]]
#> # A tibble: 2 x 6
#>   term        estimate std.error statistic    p.value country    
#>   <chr>          <dbl>     <dbl>     <dbl>      <dbl> <fct>      
#> 1 (Intercept) -53730.    6773.       -7.93 0.0000127  Philippines
#> 2 year            28.2      3.42      8.25 0.00000895 Philippines

continents <- unique(readd(continent))
index <- which(continents == "Oceania")
readd(results, subtargets = index)
#> [[1]]
#> # A tibble: 4 x 7
#>   term       estimate std.error statistic      p.value country    continent
#>   <chr>         <dbl>     <dbl>     <dbl>        <dbl> <fct>      <fct>    
#> 1 (Intercep… -824973.   47418.      -17.4      8.34e-9 Australia  Oceania  
#> 2 year           427.      24.0      17.8      6.61e-9 Australia  Oceania  
#> 3 (Intercep… -459336.   26886.      -17.1      9.96e-9 New Zeala… Oceania  
#> 4 year           241.      13.6      17.7      6.96e-9 New Zeala… Oceania
```

<sup>Created on 2019-11-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wlandau** [comment]
FYI, I decided to extend dynamic `combine()` to work with static targets. Could be useful in non-row-wise data splitting situations.

``` r
library(broom)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(drake)
library(gapminder)

fit_model <- function(dataset, country) {
  dataset %>%
    lm(formula = gdpPercap ~ year) %>%
    tidy() %>%
    mutate(country = !!country)
}

plan <- drake_plan(
  dataset = gapminder,
  country = dataset$country,
  model = target(
    fit_model(dataset, country),
    dynamic = combine(dataset, .by = country)
  )
)

make(plan, verbose = 0L)

readd(model, subtargets = 1)
#> [[1]]
#> # A tibble: 2 x 6
#>   term        estimate std.error statistic p.value country    
#>   <chr>          <dbl>     <dbl>     <dbl>   <dbl> <fct>      
#> 1 (Intercept) 1675.      3747.       0.447   0.664 Afghanistan
#> 2 year          -0.441      1.89    -0.233   0.821 Afghanistan
```

<sup>Created on 2019-11-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wlandau** [comment]
New chapter in the manual: https://ropenscilabs.github.io/drake-manual/dynamic.html

**Comment by mik3y64** [comment]
Thanks wlandau you are killing it. Dynamic branching is here! This is a big improvement for large plan. 

Now we have two choices of static and dynamic branching. One thing now I am confuse that, as mentioned in the new chapter of manual, with all the benefits of dynamic branching, from performance improvement of `drake_config` and `outdated` to flexibility of using unknown targets in advance, and now even dynamic branching can be used for static branching?

```
plan <- drake_plan(
  static_numbers = seq_len(2),
  static_letters = c("a", "b"),
  dynamic_lowercase = target(
    paste0(static_numbers, static_letters),
    dynamic = map(static_numbers, static_letters)
  ),
  dynamic_uppercase = target(
    toupper(dynamic_lowercase),
    dynamic = map(dynamic_lowercase)
  )
)
```

What are the pros and cons of static and dynamic branching and how do we choose between them? Can dynamic branching be a drop-in replacement for static branching in most cases?

**Comment by wlandau** [comment]
With dynamic branching, `make()` is faster to initialize, and you have far more flexibility. With static branching, you have meaningful target names, and it is easier to predict what the plan is going to do in advance. I think that is the crux of it. As you say, there is a ton of room for overlap and personal judgement.

In fact, you can even use static and dynamic branching together! If you do, I recommend static `map()` for small expansions and dynamic `map()`s for large expansions. Sketch:

``` r
library(drake)

plan <- drake_plan(
  locations = get_location_db(), # many rows
  coordinates = target(
    my_geocode_fn(locations, method),
    dynamic = map(locations),
    transform = map(method = c("address", "postal", "boundary"))
  ),
  results = target(
    bind_rows(coordinates),
    dynamic = combine(coordinates),
    transform = combine(coordinates)
  )
)

plot(plan)
```



<sup>Created on 2019-11-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wlandau** [comment]
And thanks for the question, @mik3y64. I think this is a good one for the manual.

**Pull request merged**
