### PR TITLE
make(session = callr::r_vanilla)

### PR DESCRIPTION
**Pull request by wlandau**
# Summary

Adds a `session` argument to `make()` and `drake_config()` to optionally tell `make_with_config()` to operate in a new, fresh, isolated master session. Example with [`reprex`](https://github.com/tidyverse/reprex):

```r
library(drake)
#> Warning: replacing previous import 'graph::addNode' by 'XML::addNode' when
#> loading 'CodeDepends'
#> Warning: replacing previous import 'graph::plot' by 'graphics::plot' when
#> loading 'CodeDepends'
clean(destroy = TRUE)
load_basic_example()
make(my_plan, session = callr::r_vanilla)
outdated(drake_config(my_plan))
#> character(0)
```

Benefits:
- Enhanced reproducibility.
- A more thorough solution to the problem #253 and #296 were trying to solve.

Drawbacks:
- Extra overhead to set up the new session.
- Extra overhead and clutter to copy the imported globals to the new session.
- I needed to set `libpath` to `.libPaths()`, so reproducibility is not perfect.
- To make sure this feature gets tested correctly, I needed to temporarily alter the global environment in a unit test. Afterwards, I do try to remove any objects created during `make()`, but this is still bad form.

cc @rkrug, @AlexAxthelm, @krlmlr.

# GitHub issues fixed

- Ref: #333

# Checklist

- [x] I have read `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CONDUCT.md), and I agree to follow its rules.
- [x] I have read the [guidelines for contributing](https://github.com/ropensci/drake/blob/master/CONTRIBUTING.md).
- [x] I have listed any substantial changes in the [development news](https://github.com/ropensci/drake/blob/master/NEWS.md).
- [x] I have added [`testthat`](https://github.com/r-lib/testthat) unit tests to [`tests/testthat`](https://github.com/ropensci/drake/tree/master/tests/testthat) to confirm that any new features or functionality work correctly.
- [x] I have tested this pull request locally with `devtools::check()`
- [x] This pull request is ready for review.
- [x] I think this pull request is ready to merge.

### CODE REVIEW

**Comment by rkrug** [comment]
Mo objections - it looks fine, although I don't have any time to test it. Will do that beginning of next week.

**Comment by rkrug** [comment]
Thinking about it - would it be necessary to also use the `session` in the generation of graphs? The dependency graph is influenced by the environment (see #335 for problem this can cause)?

Must admit, havern't looked at the code yet...

**Comment by wlandau** [comment]
Unfortunately, we really do need the original session to build the graph. That way, we know which global imports we need to transfer to the new session. The alternative is just to copy over everything from `globalenv()`, which is not good for reproducibility. If you really want to avoid to avoid things from the global environment, you can define your functions in your own separate environment and pass it to `make()`.

```r
library(drake)
#> Warning: replacing previous import 'graph::addNode' by 'XML::addNode' when
#> loading 'CodeDepends'
#> Warning: replacing previous import 'graph::plot' by 'graphics::plot' when
#> loading 'CodeDepends'
clean(destroy = TRUE)
envir <- new.env(parent = baseenv())
evalq({
  f <- function(x) {
    g(x) + 1
  }
  g <- function(x) {
    x + 1
  }
}, envir = envir)
plan <- drake_plan(y = f(1))
make(plan, envir = envir, session = callr::r_vanilla)
readd(y)
#> [1] 3
```

**Comment by rkrug** [comment]
But this only impacts on the graph, or also the functioning of the compilation of the targets - right? So this is not a serious limitation for the repoducability of the targets / make process, but only for the dependency graph?

**Comment by wlandau** [comment]
Sorry, I am not sure what you mean.

**Pull request merged**
