### PR TITLE
List example real-world projects

### PR DESCRIPTION
**Pull request by wlandau**
# Summary

In this PR, I list some example real-world projects that use `drake`. Before merging, I would like to consult the authors. @AlexAxthelm, @efcaguab, @krlmlr, and @tiernanmartin, may I link to these projects in the README?

- [`dplyr`](https://github.com/tidyverse/dplyr) (for [checking reverse dependencies](https://github.com/tidyverse/dplyr/tree/master/revdep))
- [efcaguab/demografia-del-voto](https://github.com/efcaguab/demografia-del-voto)
- [efcaguab/great-white-shark-nsw](https://github.com/efcaguab/great-white-shark-nsw)
- [IndianaCHE/Detailed-SSP-Reports](https://github.com/IndianaCHE/Detailed-SSP-Reports)
- [tiernanmartin/home-and-hope](https://github.com/tiernanmartin/home-and-hope)

# GitHub issues fixed

none

# Checklist

- [x] I have read `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CONDUCT.md), and I agree to follow its rules.
- [x] I have read the [guidelines for contributing](https://github.com/ropensci/drake/blob/master/CONTRIBUTING.md).
- [x] I have listed any substantial changes in the [development news](https://github.com/ropensci/drake/blob/master/NEWS.md).
- [x] I have added [`testthat`](https://github.com/r-lib/testthat) unit tests to [`tests/testthat`](https://github.com/ropensci/drake/tree/master/tests/testthat) to confirm that any new features or functionality work correctly.
- [x] I have tested this pull request locally with `devtools::check()`
- [x] This pull request is ready for review.
- [ ] I think this pull request is ready to merge.

### CODE REVIEW

**Comment by AlexAxthelm** [comment]
I'm totally okay with adding a link to `IndianaCHE/Detailed-SSP-Reports`. I'll be sure to add a note somewhere in the repo that it's still in development, but I think it's a good example of how `drake` can manage a workflow that would be ...unpleasant with a `makefile`

**Comment by tiernanmartin** [comment]
Fine by me.

I'll see if I can add a README to describe the project.

**Comment by krlmlr** [comment]
Revdep checking is work in progress, I'd rather wait before publicizing it.

**Comment by wlandau** [comment]
Thanks for letting me know, Kirill. I have removed the mention via https://github.com/ropensci/drake/pull/352/commits/4f6950a5bf2a55cc6971728f50d910dfb19a4741.

**Comment by wlandau** [comment]
Closing in favor of f7a608f8e335514951f9d321ee2e8bf7e7e8e34c. So far, I just referenced https://github.com/IndianaCHE/Detailed-SSP-Reports and https://github.com/tiernanmartin/home-and-hope. @efcaguab, I would love to include https://github.com/efcaguab/demografia-del-voto and https://github.com/efcaguab/great-white-shark-nsw if you are willing.

**Comment by efcaguab** [comment]
Hi. Yes, it’s ok to include those repositories. 

Cheers,
Fernando

**Comment by wlandau** [comment]
Wonderful, thanks!

**Pull request closed without merging**
