### PR TITLE
Option to redirect informal console messages to a file

### PR DESCRIPTION
**Pull request by wlandau**
# Summary

If `verbose` is `> 0`, `make()` outputs progress `message()`s to the console.

```r
make(my_plan)
#> target large
#> target small
#> ...
```

In this PR, `make(console = "log.txt")` appends these messages to the file `"log.txt"`. That way, users can just inspect a log file instead of polling `progress()`, and we avoid the issues described in https://github.com/HenrikBengtsson/future/issues/171#issuecomment-339442682.

Note: if you want to suppress color coding characters, you will need to call `options(crayon.enabled = FALSE)` in your session and possibly `make(prework = "options(crayon.enabled = FALSE)")`.

cc @lorenzwalthert

# Related GitHub issues

- Ref: #400

# Checklist

- [x] I have read `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CONDUCT.md), and I agree to follow its rules.
- [x] I have read the [guidelines for contributing](https://github.com/ropensci/drake/blob/master/CONTRIBUTING.md).
- [x] I have listed any substantial changes in the [development news](https://github.com/ropensci/drake/blob/master/NEWS.md).
- [x] I have added [`testthat`](https://github.com/r-lib/testthat) unit tests to [`tests/testthat`](https://github.com/ropensci/drake/tree/master/tests/testthat) to confirm that any new features or functionality work correctly.
- [x] I have tested this pull request locally with `devtools::check()`
- [x] This pull request is ready for review.
- [x] I think this pull request is ready to merge.

### CODE REVIEW

**Comment by wlandau** [comment]
@lorenzwalthert, I am not sure I know what you mean. In `make(console = NULL)` (default), `drake` uses `message(msg)` to tell the user about the targets, imports, and checks it goes through (depending on the `verbose` argument). In `make(console = "log.txt")`, `drake` calls `write(msg, "log.txt")` instead. (See [write_to_console()](https://github.com/ropensci/drake/blob/e6f3788f0cabb24445cebf20ee725f26a214f1f5/R/console.R#L175).) Overall, `drake` restricts itself to `message()`, `warning()` and `stop()` to print things. It previously used `cat()`, but I switched all those calls to `message()` in late 2017.

**Comment by wlandau** [comment]
`drake` also captures messages, warnings, and errors generated by individual targets (see [run_command()](https://github.com/ropensci/drake/blob/b76a5839e4c5e95b3b95c008af86fb5af84d1ef5/R/run.R#L21)). These side effects are stored with the rest of the metadata, and you can retrieve them later with `diagnose()`. `drake` does not currently capture regular `stdout()` outputs from `print()`, `cat()`, etc.

**Comment by lorenzwalthert** [comment]
Thanks. Maybe I was not specific enough, so here's the reprex:
```r
library(drake)
futile.logger::flog.appender(futile.logger::appender.file("futile-logger"), 
  name = "default")
#> NULL
options(crayon.enabled = FALSE)
just_some_random_communication <- function(a) {
  cat("cat")
  print("print")
  warning("warning")
  message("message")
  as.integer("L")
  futile.logger::flog.error("This is an error", name = "default")
}

plan <- drake_plan(random = just_some_random_communication(4))
clean()
unlink(c("drake-logger", "futile-logger"))
make(plan, seed = 200, console = "drake-logger")
#> cat[1] "print"
#> Warning in just_some_random_communication(4): warning
#> message
#> Warning in just_some_random_communication(4): NAs introduced by coercion
#> Warning: target random warnings:
#>   warning
#>   NAs introduced by coercion
#> Target random messages:
#>   message
readLines("drake-logger")
#> [1] "target random"
readLines("futile-logger")
#> [1] "ERROR [2018-05-31 23:26:27] This is an error"
```
I think in principle it would be nice to have the warnings and messages created inside the functions inside the drake plan sent to the logging file too instead of the console. But as I said, it does not seem to be a super pressing issue.

I tried to play around a bit with `sink()` but I could not figure it out. And `capture.output()` seems too radical.

**Comment by wlandau** [comment]
I suppose we could write other messages to the log too, plus warnings and errors. For what it's worth, the log does tell you if a target failed.

**Comment by wlandau** [comment]
Update: from 2b0fff2c6774f7b12646fdd792e294990108f050, the log file should now catch errors, warnings, and messages. Regular output from `cat()` is not yet captured.

Also, if you specify a file with `make(console = "log.txt")`, `crayon` characters are suppressed.

**Comment by wlandau** [comment]
And from 7f603e7893b94583ab566795c1965e6130fafb56, `stdout` output from `cat()` etc. is captured too.

```r
library(drake)
futile.logger::flog.appender(futile.logger::appender.file("futile-logger"), 
  name = "default")
#> NULL
options(crayon.enabled = FALSE)
just_some_random_communication <- function(a) {
  cat("cat")
  print("print")
  warning("warning")
  message("message")
  as.integer("L")
  futile.logger::flog.error("This is an error", name = "default")
}
plan <- drake_plan(random = just_some_random_communication(4))
clean()
unlink(c("drake-logger", "futile-logger"))
make(plan, seed = 200, console = "drake-logger")
#> Warning in just_some_random_communication(4): warning
#> message
#> Warning in just_some_random_communication(4): NAs introduced by coercion
#> Warning: target random warnings:
#>   warning
#>   NAs introduced by coercion
cat(readLines("drake-logger"), sep = "\n")
#> target random
#> Warning: target random warnings:
#>   warning
#>   NAs introduced by coercion
#> Target random messages:
#>   message
#> Target random console output:
#>   cat[1] "print"
cat(readLines("futile-logger"), sep = "\n")
#> ERROR [2018-06-01 12:49:27] This is an error
```

**Comment by wlandau** [comment]
On second thought, I do not think it is a good idea to capture `stdout` from the user's calls to `print()` or `cat()`. People like to print progress and informally time things with `print()` statements, and I do not think `drake` should interfere with this. Reverted in 881746442e961edd3931989c12e1aaa1deb12aa6.

**Comment by lorenzwalthert** [comment]
Thanks so much @wlandau 😊. I just tried quickly and it works as expected. I can even use the same log file for `futile.logger` and the terminal output. This is exactly what I wanted. 👍 .

Obviously I can't foresee all use-cases, but it seems to make sense to reserve `print()` and `cat()` to be always sent to the console, e.g. for debugging. One could write a wrapper with `capture.output()` or similar around functions that use `cat()` and `print()` in an unexpected manner to keep a clean console.

**Comment by wlandau** [comment]
Update: in 1a77aaeb56780a46c884ee0ff4f6d2f592e04a26, I changed the `console` argument to `console_log_file`. Much clearer this way.

**Pull request merged**
