### PR TITLE
use_cache = TRUE for loadd()

### LINKED ISSUE #301: Cache not used with loadd(lazy = "bind")?
``` r
library(drake)
plan <- drake_plan(
  x = rep(0L, 1e8)
)
make(plan)
#> cache /tmp/RtmpStboXf/.drake
#> connect 1 import: plan
#> connect 1 target: x
#> check 1 item: rep
#> check 1 item: x
#> target x
loadd(x, lazy = "bind")
#> cache /tmp/RtmpStboXf/.drake
#> Replacing already-loaded variable x with an active binding.
system.time(length(x))
#>    user  system elapsed 
#>   1.435   0.088   1.522
system.time(length(x))
#>    user  system elapsed 
#>   1.376   0.084   1.460
system.time(length(x))
#>    user  system elapsed 
#>   1.393   0.076   1.469
```

> Created on 2018-03-06 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

### PR DESCRIPTION
**Pull request by krlmlr**
Closes #301.

### CODE REVIEW

**Comment by krlmlr** [comment]
Now:

``` r
library(drake)
plan <- drake_plan(
  x = rep(0L, 1e8)
)
make(plan)
#> cache /tmp/Rtmp3WqoOs/.drake
#> connect 1 import: plan
#> connect 1 target: x
#> check 1 item: rep
#> check 1 item: x
#> target x
loadd(x, lazy = "bind")
#> cache /tmp/Rtmp3WqoOs/.drake
#> Replacing already-loaded variable x with an active binding.
system.time(length(x))
#>    user  system elapsed 
#>   1.763   0.148   1.911
system.time(length(x))
#>    user  system elapsed 
#>   0.001   0.000   0.001
system.time(length(x))
#>    user  system elapsed 
#>   0.001   0.000   0.000
```

> Created on 2018-03-06 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by wlandau-lilly** [comment]
Thanks, Kirill. I meant to set `use_cache = TRUE` there, but it turns out I set it to `TRUE` [here](https://github.com/krlmlr/drake/blob/52785d6eacf2d2d02b7318fa279945135d20f054/R/read.R#L55) by mistake.

**Comment by krlmlr** [comment]
Thanks. It doesn't look entirely wrong to use caching with `readd()` too. How do you decide if you use `use_cache = TRUE` or `= FALSE` ?

**Comment by wlandau-lilly** [comment]
I am mainly concerned with the many targets loaded by `prune_environment()` during `make()`. It seems like memory usage could easily get out of hand for large projects if `use_cache = TRUE` there. Alternatively, maybe the memory caching in `storr` could somehow replace `prune_environment()` entirely. I should ask Rich.

**Comment by krlmlr** [comment]
I'd expect *storr* to limit the cache size.?

**Pull request merged**
