### PR TITLE
Automated data recovery

### PR DESCRIPTION
**Pull request by wlandau**
# Summary

This PR is for discussion only. I am not sure it would be best to follow through just yet. It may or may not end up as an experimental feature in the next release. Either way, I would really like to learn what users think.

When you call `clean()` without garbage collection (default) the actual target data is still in the cache. That means we can implement automated data recovery. We can skip a target's command if the dependencies etc. are shared by an old target whose value we still have.

``` r
library(drake)
library(tidyverse)

plan <- drake_plan(
  x = iris %>%
    group_by(Species) %>%
    summarize_all(mean)
)

make(plan)
#> target x

# Invalidate the target.
clean()

# The data is still there.
make(plan, recover = TRUE)
#> recover x

# Change x.
plan <- drake_plan(
  x = iris %>%
    group_by(Species) %>%
    summarize_all(sum)
)

make(plan)
#> target x

# Change it back.
plan <- drake_plan(
  x = iris %>%
    group_by(Species) %>%
    summarize_all(mean)
)

make(plan, recover = TRUE)
#> recover x

# If we set a custom seed,
# we can rename the target
# without rebuilding it.
plan <- drake_plan(
  x = target(
    iris %>%
      group_by(Species) %>%
      summarize_all(sum),
    seed = 123
  )
)

# `recover` is TRUE, but the dependencies do not match
# those of a previous build in the cache.
make(plan, recover = TRUE)
#> target x

plan <- drake_plan(
  y = target(
    iris %>%
      group_by(Species) %>%
      summarize_all(sum),
    seed = 123
  )
)

make(plan, recover = TRUE)
#> recover y
```

<sup>Created on 2019-07-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

But this approach has problems.

1. Reproducibility. We do not know how far back these old targets go. We might be pulling data from old R versions and package environments that no longer exist.
2. Performance. For a [large number of empty targets](https://github.com/wlandau/drake-examples/tree/master/overhead), the extra bookkeeping incurs a 7.5% runtime penalty. Plus, the implementation requires lots of tiny files that encumber the cache.

# Related GitHub issues and pull requests

- Ref: #945

# Checklist

- [x] I understand and agree to `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] I have listed any substantial changes in the [development news](https://github.com/ropensci/drake/blob/master/NEWS.md).
- [x] I have added [`testthat`](https://github.com/r-lib/testthat) unit tests to [`tests/testthat`](https://github.com/ropensci/drake/tree/master/tests/testthat) for any new functionality.
- [x] This pull request is not a [draft](https://github.blog/2019-02-14-introducing-draft-pull-requests).

### CODE REVIEW

**Comment by wlandau** [comment]
Another issue: the implementation requires direct access to `config$cache$driver$set_hash()`, which is not part of the unified `storr` API. We have `set_hash()` in the RDS, environment, and DBI drivers (which I think are the ones we care about the most) but not necessarily in all drivers. `drake` does check if we have a `set_hash()` method before we try to recover old targets. But is it still okay to use a driver method directly? cc @richfitz.

**Comment by richfitz** [comment]
`set_hash` is part of the `storr` spec, so all drivers should have it with no need to check: https://github.com/richfitz/storr/blob/5c5475224b7311128e2fcee456280fa7b97499b8/inst/spec/test-driver.R#L31-L70

The difference is in what these functions will accept, which you can get by querying the drivers traits.

**Comment by wlandau** [comment]
Awesome, thanks for clarifying. What about `hash_algorithm`? It is a trait of the more commonly used drivers, but I do not see it in the spec.

**Comment by richfitz** [comment]
https://github.com/richfitz/storr/blob/5c5475224b7311128e2fcee456280fa7b97499b8/inst/spec/test-storr.R#L185-L229 - looks like I never made it a required trait.  So you can test the `$hash_algorithm` logical trait to see if it's supported

**Comment by wlandau** [comment]
Hmm... I suppose I will have to enforce it in `drake`. Glad I know now.

**Comment by wlandau** [comment]
Back to the main thread: after some more commits, I think the main concerns are mostly alleviated.

1. Reproducibility. The latest commit takes some precautions. `make(recover = FALSE, recoverable = TRUE)` is the default. The data is automatically indexed for potential recovery, but you have to opt into the actually take advantage of the recovery itself. Once you do, you can see when a target's data was actually stored using `diagnose(my_target)$date`.
2. Speed. I refactored the implementation to avoid saving extra stuff to `.drake/data/`, which shaved off 50% of the overhead. Now, it takes less time to make data recoverable than it does to track progress.
3. `storr` API: we are allowed to use `set_hash()`.

Let's make this an experimental feature in the next release.

**Pull request merged**
