### PR TITLE
Data splitting

### PR DESCRIPTION
**Pull request by wlandau**
# Summary

cc @kendonB, @AlexAxthelm.

This PR introduces `drake_slice()`, a standalone function to help split data across multiple targets. It is like `split()`, but more powerful:

1. It only takes *one* element of the partition.
2. It can split arbitrary data (lists, matrices, arrays, and data frames) over any one-dimensional margin (rows, columns, etc).
3. It is *faster*.

# Standalone usage

``` r
library(drake)
x <- matrix(seq_len(20), nrow = 5)
x
#>      [,1] [,2] [,3] [,4]
#> [1,]    1    6   11   16
#> [2,]    2    7   12   17
#> [3,]    3    8   13   18
#> [4,]    4    9   14   19
#> [5,]    5   10   15   20
drake_slice(x, splits = 3, index = 1)
#>      [,1] [,2] [,3] [,4]
#> [1,]    1    6   11   16
#> [2,]    2    7   12   17
drake_slice(x, splits = 3, index = 2)
#>      [,1] [,2] [,3] [,4]
#> [1,]    3    8   13   18
#> [2,]    4    9   14   19
drake_slice(x, splits = 3, index = 3)
#>      [,1] [,2] [,3] [,4]
#> [1,]    5   10   15   20
drake_slice(x, splits = 3, margin = 2, index = 1)
#>      [,1] [,2]
#> [1,]    1    6
#> [2,]    2    7
#> [3,]    3    8
#> [4,]    4    9
#> [5,]    5   10
```

<sup>Created on 2019-05-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

# In drake

``` r
library(drake)
plan <- drake_plan(
  large_data = iris,
  data_split = target(
    drake_slice(large_data, splits = 50, index = i),
    transform = map(i = !!seq_len(50))
  )
)
plan
#> # A tibble: 51 x 2
#>    target        command                                         
#>    <chr>         <expr>                                          
#>  1 large_data    iris                                            
#>  2 data_split_1L drake_slice(large_data, splits = 50, index = 1L)
#>  3 data_split_2L drake_slice(large_data, splits = 50, index = 2L)
#>  4 data_split_3L drake_slice(large_data, splits = 50, index = 3L)
#>  5 data_split_4L drake_slice(large_data, splits = 50, index = 4L)
#>  6 data_split_5L drake_slice(large_data, splits = 50, index = 5L)
#>  7 data_split_6L drake_slice(large_data, splits = 50, index = 6L)
#>  8 data_split_7L drake_slice(large_data, splits = 50, index = 7L)
#>  9 data_split_8L drake_slice(large_data, splits = 50, index = 8L)
#> 10 data_split_9L drake_slice(large_data, splits = 50, index = 9L)
#> # … with 41 more rows
make(plan, verbose = FALSE)
readd(data_split_1L)
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> 1          5.1         3.5          1.4         0.2  setosa
#> 2          4.9         3.0          1.4         0.2  setosa
#> 3          4.7         3.2          1.3         0.2  setosa
readd(data_split_2L)
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> 4          4.6         3.1          1.5         0.2  setosa
#> 5          5.0         3.6          1.4         0.2  setosa
#> 6          5.4         3.9          1.7         0.4  setosa
```

<sup>Created on 2019-05-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

# Performance

``` r
library(drake)
data <- data.frame(x = rnorm(1e7), y = rnorm(1e7), split = rep(seq_len(1e3), each = 1e3))
in_drake <- function(data) {
  lapply(
    seq_len(1e3),
    function(index) {
      drake_slice(data = data, margin = 1, splits = 1e3, index = index)
    }
  )
}
microbenchmark::microbenchmark(
  in_drake(data),
  split(data, data$split)
)
#> Unit: milliseconds
#>                     expr      min       lq     mean   median       uq
#>           in_drake(data) 658.8799 722.5818 739.9482 739.2865 760.0638
#>  split(data, data$split) 781.2605 823.5777 854.2063 851.5961 884.0709
#>        max neval
#>   809.2433   100
#>  1012.5042   100
```

<sup>Created on 2019-05-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Like `parallel::splitIndices()`, `drake_split()` distributes the data roughly uniformly. But again, `drake_split()` is faster. Let's compare `parallel::splitIndices()` to `drake:::slice_indices()`.

``` r
library(parallel)
in_drake <- function(n, splits) {
  out <- list()
  for (i in seq_len(splits)) {
    out[[i]] <- drake:::slice_indices(n, splits, index = i)
  }
  out
}
microbenchmark::microbenchmark(
  x = splitIndices(1e7, 1e4),
  y = in_drake(1e7, 1e4)
)
#> Unit: milliseconds
#>  expr       min        lq      mean    median        uq       max neval
#>     x 1756.5093 1838.7770 1875.7965 1858.2513 1909.8502 2060.6485   100
#>     y  188.1675  233.6143  257.0295  249.3103  273.1486  492.9323   100
```

<sup>Created on 2019-05-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

# Related GitHub issues and pull requests

- Ref: #77, #685, #833

# Checklist

- [x] I understand and agree to `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] I have listed any substantial changes in the [development news](https://github.com/ropensci/drake/blob/master/NEWS.md).
- [x] I have added [`testthat`](https://github.com/r-lib/testthat) unit tests to [`tests/testthat`](https://github.com/ropensci/drake/tree/master/tests/testthat) for any new functionality.
- [x] This pull request is not a [draft](https://github.blog/2019-02-14-introducing-draft-pull-requests).

### CODE REVIEW

**Comment by kendonB** [comment]
Great! Looking forward to trying it out. May I ask why you went with `drake_slice` and not `drake_split`? The former makes me think it's somehow analogous to `dplyr::slice` which it doesn't seem to be.

**Comment by wlandau** [comment]
As I understand it, splitting keeps all the subsets (going by `split()`), whereas `drake_slice()` and slicing in general are about taking a single subset at a time.

**Comment by kendonB** [comment]
My look was too casual. I see the logic now. However, is it worth taking away more boiler plate and just having:
```
drake_split(large_data, splits = 50)
```
instead of:
```
target(
    drake_slice(large_data, splits = 50, index = i),
    transform = map(i = !!seq_len(50))
  )
```
?

**Comment by wlandau** [comment]
I will think about it. At this point, however, it seems like a nontrivial complexity penalty with comparatively little gain in convenience. I could be convinced otherwise, but that is how I am leaning now.

**Comment by wlandau** [comment]
For a special DSL function to be worth the trouble, I think this tactic needs to solve more problems than we have identified so far. For example, could we use `drake_slice()` to avoid loading the entire dataset into memory? Could @jimhester's new [`vroom`](https://github.com/r-lib/vroom) package help us? From the README, it seems as though `x <- vroom("file.csv")[1:5, ]` should only read the first 5 rows of a file into memory. If so, then `make(jobs = 50, parallelism = "clustermq")` on the following plan should only load 2% of the data into memory on each node. @kendonB, I am sure that would help the massive projects you work on.

```r
plan <- drake_plan(
  large_data = iris,
  data = vroom(file_in("large_data.csv")),
  analysis = target(
    drake_slice(data, slices = 50, index = i) %>% # I am about to change `splits` to `slices`.
      large_computation(),
    transform = map(i = !!seq_len(50))
  )
)
```

In that case, it will totally be worth the syntactic sugar of

```r
plan <- drake_plan(
  large_data = iris,
  data = vroom(file_in("large_data.csv")),
  analysis = target(
    data %>%
      large_computation(),
    transform = split(data, .slices = 50)
  )
)
```

**Comment by wlandau** [comment]
The [speed benchmarks of `vroom`](http://vroom.r-lib.org/articles/benchmarks.html) are super impressive, and it seems like speed was the primary motivator. However, I am not sure it addresses https://github.com/ropensci/drake/pull/876#issuecomment-494211826. I have included some memory benchmarks.

``` r
dir_csv <- tempfile()
file_zip <- tempfile()
file_csv <- tempfile()
downloader::download(
    "http://eforexcel.com/wp/wp-content/uploads/2017/07/1500000%20Sales%20Records.zip", # nolint
    file_zip,
    quiet = TRUE
)
dir.create(dir_csv)
utils::unzip(file_zip, exdir = dir_csv)
tmp <- file.rename(
  file.path(dir_csv, list.files(dir_csv, pattern = "csv$")[1]),
  file_csv
)
write("", file_csv, append = TRUE, sep = "\n")

baseline <- pryr::mem_used()
#> Registered S3 method overwritten by 'pryr':
#>   method      from
#>   print.bytes Rcpp
x <- readr::read_csv(file_csv)
#> Parsed with column specification:
#> cols(
#>   Region = col_character(),
#>   Country = col_character(),
#>   `Item Type` = col_character(),
#>   `Sales Channel` = col_character(),
#>   `Order Priority` = col_character(),
#>   `Order Date` = col_character(),
#>   `Order ID` = col_double(),
#>   `Ship Date` = col_character(),
#>   `Units Sold` = col_double(),
#>   `Unit Price` = col_double(),
#>   `Unit Cost` = col_double(),
#>   `Total Revenue` = col_double(),
#>   `Total Cost` = col_double(),
#>   `Total Profit` = col_double()
#> )
mem_readr <- pryr::mem_used() - baseline

baseline <- pryr::mem_used()
y <- vroom::vroom(file_csv)
#> Observations: 1,500,000
#> Variables: 14
#> chr [7]: Region, Country, Item Type, Sales Channel, Order Priority, Order Date, Shi...
#> dbl [7]: Order ID, Units Sold, Unit Price, Unit Cost, Total Revenue, Total Cost, To...
#> 
#> Call `spec()` for a copy-pastable column specification
#> Specify the column types with `col_types` to quiet this message
mem_vroom <- pryr::mem_used() - baseline

mem_readr
#> 188 MB
mem_vroom
#> 86.3 MB

files <- c(dir_csv, file_zip, file_csv)
unlink(files, recursive = TRUE, force = TRUE)
```

<sup>Created on 2019-05-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ──────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.6.0 (2019-04-26)
#>  os       macOS Mojave 10.14.3        
#>  system   x86_64, darwin15.6.0        
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       America/Indiana/Indianapolis
#>  date     2019-05-22                  
#> 
#> ─ Packages ──────────────────────────────────────────────────────────────
#>  package     * version    date       lib
#>  assertthat    0.2.1      2019-03-21 [1]
#>  backports     1.1.4      2019-04-10 [1]
#>  callr         3.2.0      2019-03-15 [1]
#>  cli           1.1.0.9000 2019-05-13 [1]
#>  codetools     0.2-16     2018-12-24 [1]
#>  crayon        1.3.4      2017-09-16 [1]
#>  desc          1.2.0      2018-05-01 [1]
#>  devtools      2.0.2      2019-04-08 [1]
#>  digest        0.6.19     2019-05-20 [1]
#>  downloader    0.4        2015-07-09 [1]
#>  evaluate      0.13       2019-02-12 [1]
#>  fs            1.3.1      2019-05-06 [1]
#>  glue          1.3.1      2019-03-12 [1]
#>  highr         0.8        2019-03-20 [1]
#>  hms           0.4.2      2018-03-10 [1]
#>  htmltools     0.3.6      2017-04-28 [1]
#>  knitr         1.23       2019-05-18 [1]
#>  magrittr      1.5        2014-11-22 [1]
#>  memoise       1.1.0      2017-04-21 [1]
#>  pillar        1.4.0      2019-05-11 [1]
#>  pkgbuild      1.0.3      2019-03-20 [1]
#>  pkgconfig     2.0.2      2018-08-16 [1]
#>  pkgload       1.0.2      2018-10-29 [1]
#>  prettyunits   1.0.2      2015-07-13 [1]
#>  processx      3.3.1      2019-05-08 [1]
#>  pryr          0.1.4      2018-02-18 [1]
#>  ps            1.3.0      2018-12-21 [1]
#>  purrr         0.3.2      2019-03-15 [1]
#>  R6            2.4.0      2019-02-14 [1]
#>  Rcpp          1.0.1      2019-03-17 [1]
#>  readr         1.3.1      2018-12-21 [1]
#>  remotes       2.0.4      2019-04-10 [1]
#>  rlang         0.3.4.9003 2019-05-08 [1]
#>  rmarkdown     1.12       2019-03-14 [1]
#>  rprojroot     1.3-2      2018-01-03 [1]
#>  sessioninfo   1.1.1      2018-11-05 [1]
#>  stringi       1.4.3      2019-03-12 [1]
#>  stringr       1.4.0      2019-02-10 [1]
#>  testthat      2.1.1.9000 2019-05-19 [1]
#>  tibble        2.1.1      2019-03-16 [1]
#>  tidyselect    0.2.5      2018-10-11 [1]
#>  usethis       1.5.0      2019-04-07 [1]
#>  vroom         1.0.1.9000 2019-05-22 [1]
#>  withr         2.1.2      2018-03-15 [1]
#>  xfun          0.7        2019-05-14 [1]
#>  yaml          2.2.0      2018-07-25 [1]
#>  source                              
#>  CRAN (R 3.6.0)                      
#>  CRAN (R 3.6.0)                      
#>  CRAN (R 3.6.0)                      
#>  Github (r-lib/cli@f33ef92)          
#>  CRAN (R 3.6.0)                      
#>  CRAN (R 3.6.0)                      
#>  CRAN (R 3.6.0)                      
#>  CRAN (R 3.6.0)                      
#>  Github (Eddelbuettel/digest@b4cb444)
#>  CRAN (R 3.6.0)                      
#>  CRAN (R 3.6.0)                      
#>  CRAN (R 3.6.0)                      
#>  CRAN (R 3.6.0)                      
#>  CRAN (R 3.6.0)                      
#>  CRAN (R 3.6.0)                      
#>  CRAN (R 3.6.0)                      
#>  CRAN (R 3.6.0)                      
#>  CRAN (R 3.6.0)                      
#>  CRAN (R 3.6.0)                      
#>  CRAN (R 3.6.0)                      
#>  CRAN (R 3.6.0)                      
#>  CRAN (R 3.6.0)                      
#>  CRAN (R 3.6.0)                      
#>  CRAN (R 3.6.0)                      
#>  CRAN (R 3.6.0)                      
#>  CRAN (R 3.6.0)                      
#>  CRAN (R 3.6.0)                      
#>  CRAN (R 3.6.0)                      
#>  CRAN (R 3.6.0)                      
#>  CRAN (R 3.6.0)                      
#>  CRAN (R 3.6.0)                      
#>  CRAN (R 3.6.0)                      
#>  Github (r-lib/rlang@6a232c0)        
#>  CRAN (R 3.6.0)                      
#>  CRAN (R 3.6.0)                      
#>  CRAN (R 3.6.0)                      
#>  CRAN (R 3.6.0)                      
#>  CRAN (R 3.6.0)                      
#>  Github (r-lib/testthat@4a546fa)     
#>  CRAN (R 3.6.0)                      
#>  CRAN (R 3.6.0)                      
#>  CRAN (R 3.6.0)                      
#>  Github (r-lib/vroom@d3f54d6)        
#>  CRAN (R 3.6.0)                      
#>  CRAN (R 3.6.0)                      
#>  CRAN (R 3.6.0)                      
#> 
#> [1] /Library/Frameworks/R.framework/Versions/3.6/Resources/library
```

</details>

**Comment by jimhester** [comment]
`pryr::mem_used()` is not very useful metric to measure the memory with vroom. In particular altrep vectors are not accounted for in it and in addition by default numeric columns do not use Altrep (you can use `altrep_cols = TRUE` to turn it on for everything).  In addition the delimiter index is allocated in C++, outside of the R heap, so won't be counted by functions which are only looking at the R heap, like `pryr::mem_used()`. 

If you want a more accurate measure of the memory usage of the process you need to measure the memory usage outside of R, e.g. using `ps` or similar things.

**Pull request merged**
