### PR TITLE
Embrace the tibble!

### PR DESCRIPTION
**Pull request by wlandau**
Now used for workflow plan data frames and the output of `dataframes_graph()`. Supports #169 and #247. Remaining challenges:
- Build times: https://github.com/r-lib/pillar/issues/88
- Row names are deprecated in `tibble`, so some internals around staged parallelism will need careful refactoring first.

### CODE REVIEW

**Comment by wlandau** [comment]
Main benefits:
- Printing.
- For workflow plans later on, easier integration with custom `future` evaluators and commands as expressions/language objects.

**Comment by wlandau** [comment]
I just tried. It might work if I did it differently, but it seems to turn the times into NA's.

```r
load_basic_example()
make(my_plan)
bt <- build_times()
library(lubridate)
bt$elapsed <- hms(bt$elapsed)

## In .parse_hms(..., order = "HMS", quiet = quiet) :
##   Some strings failed to parse, or all strings are NAs

head(bt)

##                     item   type elapsed   user system
## 1 coef_regression1_large target    <NA> 0.004s     0s
## 2 coef_regression1_small target    <NA> 0.004s     0s
## 3 coef_regression2_large target    <NA> 0.008s     0s
## 4 coef_regression2_small target    <NA> 0.004s     0s
## 5             data.frame import    <NA> 0.008s     0s
## 6                   knit import    <NA>  0.06s     0s
```

**Comment by wlandau** [comment]
It works for me too, but I'm not sure I like the output format:

```r
> bt$elapsed %>% lubridate::as.difftime() %>% hms::as.hms()
## 00:00:00.008
## 00:00:00.004
## 00:00:00.004
## 00:00:00.007
## 00:00:00.008
## 00:00:00.010
```

**Comment by krlmlr** [comment]
The dev version of *pillar* now uses `format()` for classed numerics, the output should be fine now.

**Pull request merged**
